[package]
name = "coolcats2"
version = "0.1.0"
authors = ["Michael Goldman <mike.goldman@allstreets.org>"]
edition = "2018"

[dependencies]
yew = "0.5.0"
stdweb = "0.4.10"

[patch.crates-io]
yew = {git = "https://github.com/DenisKolodin/yew"}
