[network]
n3h_path = "_N3H_"
n3h_persistence_path = "/tmp"
bootstrap_nodes = ["_BOOTSTRAP_"]

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "apple-----------------------------------------------------------------------------AAAM8opNM0"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "banana----------------------------------------------------------------------------AAANN98S74"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent3"
name = "HoloTester3"
public_address = "cantaloupe------------------------------------------------------------------------AAAPIbDCOo"
key_file = "holo_tester.key"

[[dnas]]
id = "coolcats"
file = "dna-src/dist/bundle.json"

[[instances]]
id = "coolcats-instance_AGENT_"
agent = "test_agent_AGENT_"
dna = "coolcats"
[instances.storage]
type = "file"
path = "tmp-storage/instance_AGENT_"

[[interfaces]]
id = "websocket-interface_AGENT_"
[[interfaces.instances]]
id = "coolcats-instance_AGENT_"
[interfaces.driver]
type = "websocket"
port = _PORT_

[logger]
type = "simple"
