[package]
name = "coolcats"
version = "0.1.0"
authors = ["Michael Goldman <mike.goldman@allstreets.org>"]
edition = "2018"

[dependencies]
hdk = {git = "https://github.com/holochain/holochain-rust", tag = "v0.0.3"}
holochain_wasm_utils = {git = "https://github.com/holochain/holochain-rust", tag = "v0.0.3"}
holochain_core_types_derive = {git = "https://github.com/holochain/holochain-rust", tag = "v0.0.3"}
serde = {version = "1.0.84", features = ["derive"]}
serde_json = "1.0.36"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
